#!../../bin/linux-x86_64/EC-DAN
#+======================================================================
# $HeadURL: https://svnpub.iter.org/codac/iter/codac/dev/units/m-epics-iter-templates/tags/CODAC-CORE-5.4.0/templates/genericBoot/ioc/st.cmd $
# $Id: st.cmd 75208 2017-02-03 09:19:23Z cesnikt $
#
# Project       : CODAC Core System
#
# Description   : ITER ioc template EPICS start up file
#
# Author(s)     : This file was generated by CODAC development toolkit
#
# Copyright (c) : 2010-2017 ITER Organization,
#                 CS 90 046
#                 13067 St. Paul-lez-Durance Cedex
#                 France
#
# This file is part of ITER CODAC software.
# For the terms and conditions of redistribution or use of this software
# refer to the file ITER-LICENSE.TXT located in the top level directory
# of the distribution package.
#
#-======================================================================

< envPaths
< envSystem
< envUser

cd "${TOP}"

############################################################################
## Register all support components
############################################################################

dbLoadDatabase "dbd/EC-DAN.dbd"
EC_DAN_registerRecordDeviceDriver pdbbase

< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/sddPreDriverConf.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/userPreDriverConf.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/threadSchedulingConf.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/dbToLoad.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/iocEC-DAN-PCF0SYSM-preSaveRestore.cmd"

############################################################################
## IOC Logging
############################################################################
iocLogInit
iocLogPrefix "${STY} : "

############################################################################
## IOC initialization
############################################################################
cd "${TOP}/db"
iocInit

< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/iocEC-DAN-PCF0SYSM-postSaveRestore.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/sddSeqToLoad.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/seqToLoad.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/sddPostDriverConf.cmd"
< "${TOP}/iocBoot/iocEC-DAN-PCF0SYSM/userPostDriverConf.cmd"


dbl > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbl"
dbior > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbior"
dbhcr > "${CODAC_VAR}/iocdump/${UNIT_NAME}/${IOC_NAME}-${IOC_BOOT_TIME}.dbhcr"

#- End-of-file marker - do not delete or add lines below!
