FROM scratch

ARG CODAC_NAME=codac_v5
ARG ENTRY_POINT=${CODAC_NAME}_entry.sh

ADD ${CODAC_NAME}.tar /

# adds Epel
RUN wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm; \
	rpm -ivh epel-release-6-8.noarch.rpm

# install qt-devel
RUN yum install -y qt5-qtbase-devel

COPY ${ENTRY_POINT} /root/${CODAC_NAME}_entry.sh
ENTRYPOINT /root/${CODAC_NAME}_entry.sh
